name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install frontend dependencies
        run: |
          cd client
          npm install

      - name: Build frontend
        run: |
          cd client
          npm run build

  build_backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install backend dependencies
        run: |
          cd server
          npm install

  test_backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install backend dependencies
        run: |
          cd server
          npm install

      - name: Run backend tests
        run: |
          cd server
          npm test

  check_code_coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install backend dependencies
        run: |
          cd server
          npm install

      - name: Run backend tests and calculate code coverage
        run: |
          cd server
          npm test -- --coverage

      - name: Check code coverage
        run: |
          cd server
          COVERAGE_THRESHOLD=90 # My defined coverage threshold
          COVERAGE_REPORT=$(<coverage/lcov-report/index.html)
          if [[ $COVERAGE_REPORT == *"<span class=\"strong\">$COVERAGE_THRESHOLD%<\/span>"* ]]; then
            echo "Code coverage is at least $COVERAGE_THRESHOLD%."
          else
            echo "Code coverage is below $COVERAGE_THRESHOLD%."
            exit 1
          fi